### PR TITLE
Add passthrough on:blur prop

### PR DESCRIPTION
**Pull request by vtpatrickeddy**
`on:blur` wasn't being passed to the underlying component.

### CODE REVIEW

**Comment by JJK96** [comment]
Can this be merged please, this fixes a problem I have

**Comment by TylerRick** [comment]
Can we merge this please? I need to be able to detect when field is blurred for validation purposes.

**Comment by TylerRick** [comment]
Does anyone know how to make npm use a specific fork containing a bug fix while waiting for maintainer to merge a pull request?

I was just going to point my `package.json` to this fork, like this:
```
  "svelte-material-ui": "https://github.com/vtpatrickeddy/svelte-material-ui.git#patch-1",
```
but that doesn't work because the repo is a monorepo. And there doesn't appear to be a way to specify a subdirectory inside it, like:
```
  "@smui/textfield": "https://github.com/vtpatrickeddy/svelte-material-ui.git/packages/textarea#patch-1",
```
(see https://github.com/npm/npm/issues/2974)

**Comment by JJK96** [comment]
Not a complete solution to your problem, but I use https://www.npmjs.com/package/patch-package to make changes to an NPM package.

**Comment by TylerRick** [comment]
Thanks, @JJK96, I didn't know about patch-package! That looks like it might be just the (hopefully temporary?) workaround I need for something like this.

**Comment by TylerRick** [comment]
Can we add `on:focus`, too?

Also, looks like this is missing from other components, like `packages/checkbox/Checkbox.svelte`?

Can we just forward/bubble _all_ events emitted by the underlying input element? I see a `use:forwardEvents` on the root `<div>` of the component. Could that also be added to the `<input>`? (Would that do what I think it would?)

**Comment by hperrin** [comment]
This has been merged through another PR for the Textfield component. I'd like to add it to other components as well.

**Comment by hperrin** [comment]
Do you want to update this PR with additions to other components?

**Comment by vtpatrickeddy** [comment]
@hperrin updated.

**Comment by TylerRick** [comment]
Thanks, @vtpatrickeddy @hperrin!

**Pull request merged**
