### PR TITLE
Fix for https://github.com/hperrin/svelte-material-ui/issues#41

### PR DESCRIPTION
**Pull request by mwamp**

### CODE REVIEW

**Comment by Eradash** [comment]
This fix my problem too! When can this be merged?

**Comment by Eradash** [comment]
I tested the fix in my project and it works well!

**Comment by hperrin** [comment]
I actually figured out a deeper problem. The way I was passing selected was causing all elements to become selected.

**Comment by hperrin** [comment]
Thank you for the help. #41 is now fixed.

**Pull request merged**
