### PR TITLE
Removed console logs in Ripple.js

### PR DESCRIPTION
**Pull request by MarcosRZ**
There were a couple of forgotten console logs in Ripple.js that were a little annoying. :)

### CODE REVIEW

**Comment by AfdhalAtiffTan** [comment]
I agree, adding an option to disable this would be appreciated.

**Comment by ifreann** [comment]
Beat me to it :^)

**Comment by itsmepetrov** [comment]
@hperrin it's so annoying while developing, please merge it and publish

**Comment by danielharrison** [comment]
@hperrin ditto. Please merge and publish

**Comment by RemyPottierFr** [comment]
@hperrin hey 👍 please merge it 🙏

**Comment by hperrin** [comment]
Hey! Sorry for the long delay! I've got time today, so I'm going on a merging spree!

**Pull request merged**
