### PR TITLE
chore: upgrade material

### PR DESCRIPTION
**Pull request by mhamrah**
bumps material to v9, but I've only done preliminary testing. wanted to help out with upgrades- happy to do additional work on your current workflow to validate.

### CODE REVIEW

**Comment by marekdedic** [comment]
Hi, as a recent user of svelte-material-ui myself, probably check out #178 - seems like this repo is in maintenance mode only.

**Comment by mhamrah** [comment]
Thanks. I tried using that, but not ready for real consumption (I did offer to help [svelte-material-design/core#1]). It uses relative paths to build across repos, and cjs/esm combos with typescript that require rollup magic I'm unfamiliar with to include. 

If this really is deprecated, perhaps acknowledging so we can swarm on something else?

**Comment by marekdedic** [comment]
Well, I'm just a lowly user, but it seems to me that the author of this is doing some maintenance work occasionally, but not responding to or accepting any PRs that change anything major.

I don't want to sound entitled and fully understand that the author does not owe the users anything. With that said, it seems to me it would be of benefit to a lot of people if @hperrin would comment on the current state of this project - should we try and post PRs and updates, or is the repo in maintenance-mode only?

**Comment by hperrin** [comment]
> Hi, as a recent user of svelte-material-ui myself, probably check out #178 - seems like this repo is in maintenance mode only.

This repo is not in maintenance mode. It's a project that I do in my free time, which I've had less of recently.


Upgrading to higher version of MDC components is a monumental task that requires a lot more work than just bumping the versions. I'm working on it today, but it's going to take a while. I'm also switching the library to the advanced method of integrating MDC, since the simple method is a constant battle between MDC components and Svelte both trying to manipulate the DOM.

**Comment by hperrin** [comment]
The latest version of SMUI, v3, is available and uses the latest version of MDC-Web. :)

**Pull request closed without merging**
